/*
*  Color definitions (RGB values taken from POV-Ray sources).
*
*  Copyright (C) 1998 Angel Jimenez Jimenez and Carlos Jimenez Moreno
*
*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful, but
*  WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*  General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

define color CWhite		{ red 1 green 1 blue 1 }
define color CBlack		{ red 0 green 0 blue 0 }
define color CRed		{ red 1 green 0 blue 0 }
define color CGreen		{ red 0 green 1 blue 0 }
define color CBlue		{ red 0	green 0	blue 1 }
define color CYellow		{ red 1	green 1 blue 0 }
define color CCyan		{ red 0 green 1 blue 1 }
define color CMagenta		{ red 1 green 0 blue 1 }

define color CDimGrey		{ red 0.329412	green 0.329412	blue 0.329412 }
define color CGrey		{ red 0.752941	green 0.752941	blue 0.752941 }
define color CLightGrey		{ red 0.658824	green 0.658824	blue 0.658824 }
define color CVLightGrey	{ red 0.80	green 0.80	blue 0.80 }

define color CAquamarine	{ red 0.439216	green 0.858824	blue 0.576471 }
define color CViolet		{ red 0.62352	green 0.372549	blue 0.623529 }
define color CBrown		{ red 0.647059	green 0.164706	blue 0.164706 }
define color CCadet		{ red 0.372549	green 0.623529	blue 0.623529 }
define color CCoral		{ red 1.0	green 0.498039	blue 0.0 }
define color CCornflower	{ red 0.258824	green 0.258824	blue 0.435294 }
define color CDark		{ red 0.184314	green 0.309804	blue 0.184314 }
define color CDarkOlive		{ red 0.309804	green 0.309804	blue 0.184314 }
define color CDarkOrchid	{ red 0.6	green 0.196078	blue 0.8 }
define color CDarkSlate		{ red 0.419608	green 0.137255	blue 0.556863 }
define color CDarkSlateGray	{ red 0.184314	green 0.309804	blue 0.309804 }
define color CDarkSlateGrey	{ red 0.184314	green 0.309804	blue 0.309804 }
define color CDarkTurquoise	{ red 0.439216	green 0.576471	blue 0.858824 }
define color CFirebrick		{ red 0.556863	green 0.137255	blue 0.137255 }
define color CForest		{ red 0.137255	green 0.556863	blue 0.137255 }
define color CGold		{ red 0.8	green 0.498039	blue 0.196078 }
define color CGoldenrod		{ red 0.858824	green 0.858824	blue 0.439216 }
define color CIndian		{ red 0.309804	green 0.184314	blue 0.184314 }
define color CKhaki		{ red 0.623529	green 0.623529	blue 0.372549 }
define color CLight		{ red 0.74902	green 0.847059	blue 0.847059 }
define color CLightSteel	{ red 0.560784	green 0.560784	blue 0.737255 }
define color CLime		{ red 0.196078	green 0.8	blue 0.196078 }
define color CMaroon		{ red 0.556863	green 0.137255	blue 0.419608 }
define color CMediumAquamarine	{ red 0.196078	green 0.8	blue 0.6 }
define color CMedium		{ red 0.196078	green 0.196078	blue 0.8 }
define color CMediumForest	{ red 0.419608	green 0.556863	blue 0.137255 }
define color CMediumGoldenrod	{ red 0.917647	green 0.917647	blue 0.678431 }
define color CMediumOrchid	{ red 0.576471	green 0.439216	blue 0.858824 }
define color CMediumSea		{ red 0.258824	green 0.435294	blue 0.258824 }
define color CMediumTurquoise	{ red 0.439216	green 0.858824	blue 0.858824 }
define color CMediumViolet	{ red 0.858824	green 0.439216	blue 0.576471 }
define color CMidnight		{ red 0.184314	green 0.184314	blue 0.309804 }
define color CNavy		{ red 0.137255	green 0.137255	blue 0.556863 }
define color COrange		{ red 1		green 0.5	blue 0.0 }
define color COrchid		{ red 0.858824	green 0.439216	blue 0.858824 }
define color CPale		{ red 0.560784	green 0.737255	blue 0.560784 }
define color CPink		{ red 0.737255	green 0.560784	blue 0.560784 }
define color CPlum		{ red 0.917647	green 0.678431	blue 0.917647 }
define color CSalmon		{ red 0.435294	green 0.258824	blue 0.258824 }
define color CSea		{ red 0.137255	green 0.556863	blue 0.419608 }
define color CSienna		{ red 0.556863	green 0.419608	blue 0.137255 }
define color CSky		{ red 0.196078	green 0.6	blue 0.8 }
define color CSteel		{ red 0.137255	green 0.419608	blue 0.556863 }
define color CTan		{ red 0.858824	green 0.576471	blue 0.439216 }
define color CThistle		{ red 0.847059	green 0.74902	blue 0.847059 }
define color CTurquoise		{ red 0.678431	green 0.917647	blue 0.917647 }
define color CWheat		{ red 0.847059	green 0.847059	blue 0.74902 }
define color CSummerSky		{ red 0.22	green 0.69	blue 0.87 }
define color CRich		{ red 0.35	green 0.35	blue 0.67 }
define color CBrass		{ red 0.71	green 0.65	blue 0.26 }
define color CCopper		{ red 0.72	green 0.45	blue 0.20 }
define color CBronze		{ red 0.55	green 0.47	blue 0.14 }
define color CBronze2		{ red 0.65	green 0.49	blue 0.24 }
define color CSilver		{ red 0.90	green 0.91	blue 0.98 }
define color CBrightGold	{ red 0.85	green 0.85	blue 0.10 }
define color COldGold		{ red 0.81	green 0.71	blue 0.23 }
define color CFeldspar		{ red 0.82	green 0.57	blue 0.46 }
define color CQuartz		{ red 0.85	green 0.85	blue 0.95 }
define color CMica              { red 0         green 0         blue 0    }
define color CNeonPink		{ red 1.00	green 0.43	blue 0.78 }
define color CDarkPurple	{ red 0.53	green 0.12	blue 0.47 }
define color CNeon		{ red 0.30	green 0.30	blue 1.00 }
define color CCoolCopper	{ red 0.85	green 0.53	blue 0.10 }
define color CMandarinOrange	{ red 0.89	green 0.47	blue 0.20 }
define color CLightWood		{ red 0.91	green 0.76	blue 0.65 }
define color CMediumWood	{ red 0.65	green 0.50	blue 0.39 }
define color CDarkWood		{ red 0.52	green 0.37	blue 0.26 }
define color CSpicyPink		{ red 1.00	green 0.11	blue 0.68 }
define color CSemiSweetChoc	{ red 0.42	green 0.26	blue 0.15 }
define color CBakersChoc	{ red 0.36	green 0.20	blue 0.09 }
define color CFlesh		{ red 0.96	green 0.80	blue 0.69 }
define color CNewTan		{ red 0.92	green 0.78	blue 0.62 }
define color CNewMidnight	{ red 0.00	green 0.00	blue 0.61 }
define color CVeryDarkBrown	{ red 0.35	green 0.16	blue 0.14 }
define color CDarkBrown		{ red 0.36	green 0.25	blue 0.20 }
define color CDarkTan		{ red 0.59	green 0.41	blue 0.31 }
define color CDkCopper		{ red 0.29	green 0.46	blue 0.43 }
define color CDustyRose		{ red 0.52	green 0.39	blue 0.39 }
define color CHunters		{ red 0.13	green 0.37	blue 0.31 }
define color CScarlet		{ red 0.55	green 0.09	blue 0.09 }

define color CMed_Purple	{ red 0.73	green 0.16	blue 0.96 }
define color CLight_Purple	{ red 0.87	green 0.58	blue 0.98 }
define color CVery_Light_Purple	{ red 0.94	green 0.81	blue 0.99 }
