/*
*  Color definitions (RGB values taken from POV-Ray sources).
*
*  Copyright (C) 1998 Angel Jimenez Jimenez and Carlos Jimenez Moreno
*
*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful, but
*  WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*  General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

define CWhite             < 1, 1, 1 >;
define CBlack             < 0, 0, 0 >;
define CRed               < 1, 0, 0 >;
define CGreen             < 0, 1, 0 >;
define CBlue              < 0, 0, 1 >;
define CYellow            < 1, 1, 0 >;
define CCyan              < 0, 1, 1 >;
define CMagenta           < 1, 0, 1 >;

define CDimGrey           < 0.329412, 0.329412, 0.329412 >;
define CGrey              < 0.752941, 0.752941, 0.752941 >;
define CLightGrey         < 0.658824, 0.658824, 0.658824 >;
define CVLightGrey        < 0.800000, 0.800000, 0.800000 >;

define CAquamarine        < 0.439216, 0.858824, 0.576471 >;
define CViolet            < 0.623520, 0.372549, 0.623529 >;
define CBrown             < 0.647059, 0.164706, 0.164706 >;
define CCadet             < 0.372549, 0.623529, 0.623529 >;
define CCoral             < 1.000000, 0.498039, 0.000000 >;
define CCornflower        < 0.258824, 0.258824, 0.435294 >;
define CDark              < 0.184314, 0.309804, 0.184314 >;
define CDarkOlive         < 0.309804, 0.309804, 0.184314 >;
define CDarkOrchid        < 0.600000, 0.196078, 0.800000 >;
define CDarkSlate         < 0.419608, 0.137255, 0.556863 >;
define CDarkSlateGray     < 0.184314, 0.309804, 0.309804 >;
define CDarkSlateGrey     < 0.184314, 0.309804, 0.309804 >;
define CDarkTurquoise     < 0.439216, 0.576471, 0.858824 >;
define CFirebrick         < 0.556863, 0.137255, 0.137255 >;
define CForest            < 0.137255, 0.556863, 0.137255 >;
define CGold              < 0.800000, 0.498039, 0.196078 >;
define CGoldenrod         < 0.858824, 0.858824, 0.439216 >;
define CIndian            < 0.309804, 0.184314, 0.184314 >;
define CKhaki             < 0.623529, 0.623529, 0.372549 >;
define CLight             < 0.749020, 0.847059, 0.847059 >;
define CLightSteel        < 0.560784, 0.560784, 0.737255 >;
define CLime              < 0.196078, 0.800000, 0.196078 >;
define CMaroon            < 0.556863, 0.137255, 0.419608 >;
define CMediumAquamarine  < 0.196078, 0.800000, 0.600000 >;
define CMedium            < 0.196078, 0.196078, 0.800000 >;
define CMediumForest      < 0.419608, 0.556863, 0.137255 >;
define CMediumGoldenrod   < 0.917647, 0.917647, 0.678431 >;
define CMediumOrchid      < 0.576471, 0.439216, 0.858824 >;
define CMediumSea         < 0.258824, 0.435294, 0.258824 >;
define CMediumTurquoise   < 0.439216, 0.858824, 0.858824 >;
define CMediumViolet      < 0.858824, 0.439216, 0.576471 >;
define CMidnight          < 0.184314, 0.184314, 0.309804 >;
define CNavy              < 0.137255, 0.137255, 0.556863 >;
define COrange            < 1.000000, 0.500000, 0.000000 >;
define COrchid            < 0.858824, 0.439216, 0.858824 >;
define CPale              < 0.560784, 0.737255, 0.560784 >;
define CPink              < 0.737255, 0.560784, 0.560784 >;
define CPlum              < 0.917647, 0.678431, 0.917647 >;
define CSalmon            < 0.435294, 0.258824, 0.258824 >;
define CSea               < 0.137255, 0.556863, 0.419608 >;
define CSienna            < 0.556863, 0.419608, 0.137255 >;
define CSky               < 0.196078, 0.600000, 0.800000 >;
define CSteel             < 0.137255, 0.419608, 0.556863 >;
define CTan               < 0.858824, 0.576471, 0.439216 >;
define CThistle           < 0.847059, 0.749020, 0.847059 >;
define CTurquoise         < 0.678431, 0.917647, 0.917647 >;
define CWheat             < 0.847059, 0.847059, 0.749020 >;
define CSummerSky         < 0.22, 0.69, 0.87 >;
define CRich              < 0.35, 0.35, 0.67 >;
define CBrass             < 0.71, 0.65, 0.26 >;
define CCopper            < 0.72, 0.45, 0.20 >;
define CBronze            < 0.55, 0.47, 0.14 >;
define CBronze2           < 0.65, 0.49, 0.24 >;
define CSilver            < 0.90, 0.91, 0.98 >;
define CBrightGold        < 0.85, 0.85, 0.10 >;
define COldGold           < 0.81, 0.71, 0.23 >;
define CFeldspar          < 0.82, 0.57, 0.46 >;
define CQuartz            < 0.85, 0.85, 0.95 >;
define CMica              < 0.00, 0.00, 0.00 >;
define CNeonPink          < 1.00, 0.43, 0.78 >;
define CDarkPurple        < 0.53, 0.12, 0.47 >;
define CNeon              < 0.30, 0.30, 1.00 >;
define CCoolCopper        < 0.85, 0.53, 0.10 >;
define CMandarinOrange    < 0.89, 0.47, 0.20 >;
define CLightWood         < 0.91, 0.76, 0.65 >;
define CMediumWood        < 0.65, 0.50, 0.39 >;
define CDarkWood          < 0.52, 0.37, 0.26 >;
define CSpicyPink         < 1.00, 0.11, 0.68 >;
define CSemiSweetChoc     < 0.42, 0.26, 0.15 >;
define CBakersChoc        < 0.36, 0.20, 0.09 >;
define CFlesh             < 0.96, 0.80, 0.69 >;
define CNewTan            < 0.92, 0.78, 0.62 >;
define CNewMidnight       < 0.00, 0.00, 0.61 >;
define CVeryDarkBrown     < 0.35, 0.16, 0.14 >;
define CDarkBrown         < 0.36, 0.25, 0.20 >;
define CDarkTan           < 0.59, 0.41, 0.31 >;
define CDkCopper          < 0.29, 0.46, 0.43 >;
define CDustyRose         < 0.52, 0.39, 0.39 >;
define CHunters           < 0.13, 0.37, 0.31 >;
define CScarlet           < 0.55, 0.09, 0.09 >;

define CMed_Purple        < 0.73, 0.16, 0.96 >;
define CLight_Purple      < 0.87, 0.58, 0.98 >;
define CVery_Light_Purple < 0.94, 0.81, 0.99 >;
