/*
*  Math Definitions -- To be used for standard math.
*
*  Copyright (C) 2001 Kevin Harris
*
*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful, but
*  WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*  General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

/* These were constants taken from <math.h> and renamed, modified for length */
define E         2.71828182845904523540; /* e */
define LOG2E     1.44269504088896340740; /* log_2 e */
define LOG10E    0.43429448190325182765; /* log_10 e */
define LN2       0.69314718055994530942; /* log_e 2 */
define LN10      2.30258509299404568402; /* log_e 10 */
define PI        3.14159265358979323846; /* pi */
define PI_2      1.57079632679489661923; /* pi/2 */
define PI_4      0.78539816339744830962; /* pi/4 */
define _1_PI     0.31830988618379067154; /* 1/pi */
define _2_PI     0.63661977236758134308; /* 2/pi */
define _2_SQRTPI 1.12837916709551257390; /* 2/sqrt(pi) */
define SQRT2     1.41421356237309504880; /* sqrt(2) */
define _1_SQRT2  0.70710678118654752440; /* 1/sqrt(2) */