
%.o: %.cpp
		@echo Compiling $<...
		${CXX} -c ${CXXFLAGS} $< -o $@

%.cpp: %.l
		@echo Generating scanner...
		${LEX} ${LEXFLAGS} $< > $@

%.cpp: %.y
		@echo Generating parser...
		@BISON_SIMPLE=${BUILD_TOP}/bison.simple ${YACC} ${BISONFLAGS} -do $(basename $@).c $<
		@mv $(basename $@).c $@

# Rules for generating dependency files
%.d: %.cpp
	@echo "Making dependency file for $<"                              ;\
        $(CXX) -c $(CXXFLAGS) -MMD $(FLAGS) -E $(@:%.d=%.cpp) -o $@ > /dev/null ;\
        cat $@ | sed -e 's/:/ $(@:%.d=%.o) $@:/g' > tmp$$                               ;\
        mv -f tmp$$ $@  

