PLUGIN_NAME = if_lens_flare
OBJ         = if_lens_flare.lo flare.lo       

if_lens_flare.lo: if_lens_flare.h
if_lens_flare.lo flare.lo: flare.h
if_lens_flare.lo: flare_std.h
if_lens_flare.lo: flare_hard.h
if_lens_flare.lo: flare_decreasing.h  
if_lens_flare.lo: flare_ring.h
if_lens_flare.lo: flare_halo.h
if_lens_flare.lo: flare_streaks.h
