PLUGIN_NAME = subdiv
OBJ         = subdiv.lo subdivvert.lo subdivedge.lo subdivface.lo

subdiv.lo subdivface.lo: subdiv.h
subdiv.lo subdivvert.lo subdivedge.lo subdivface.lo: subdivvert.h
subdiv.lo subdivvert.lo subdivedge.lo subdivface.lo: subdivedge.h
subdiv.lo subdivvert.lo subdivedge.lo subdivface.lo: subdivface.h

